### ISSUE TITLE
Unexpected token SyntaxError running tests

### ISSUE THREAD

**Issue by slarson** [markthethomas/react-testing-components-enzyme#2]
First time load of the library on Macbook air.  Just did a fresh install from the latest in the repo; no modifications.  Any ideas what is going wrong here?  Thanks!

```
Stephens-MacBook-Air:react-testing-components-enzyme slarson$ npm test

> react-testing-components-enzyme@1.0.0 test /Users/slarson/Documents/react-testing-components-enzyme
> mocha -w test/helpers/browser.js test/*.spec.js


/Users/slarson/Documents/react-testing-components-enzyme/test/helpers/browser.js:9
Object.keys(document.defaultView).forEach((property) => {
                                                     ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/slarson/Documents/react-testing-components-enzyme/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/slarson/Documents/react-testing-components-enzyme/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/slarson/Documents/react-testing-components-enzyme/node_modules/mocha/lib/mocha.js:485:10)
    at loadAndRun (/Users/slarson/Documents/react-testing-components-enzyme/node_modules/mocha/bin/_mocha:359:22)
    at Object.<anonymous> (/Users/slarson/Documents/react-testing-components-enzyme/node_modules/mocha/bin/_mocha:376:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by markthethomas** [comment]
hey @slarson, I'll take a look. Looks like a transpilation thing at first glance. Actually, no — what version of node are you running?

**Comment by slarson** [comment]
Thanks for having a look!  I'm running node v0.12.4 with npm v2.10.1 on OSX El Capitan 10.11.6.

Here's what comes out when I do an `npm list`: http://pastebin.com/spxvwRVE

**Comment by slarson** [comment]
Fixed when I upgraded node!

**Comment by markthethomas** [comment]
dang — didn't respond to this. Yeah, your version of node was pretty old. I'd recommend using [nvm](https://github.com/creationix/nvm) if you aren't already 👍
